"""
Training script for Phase 2: Synthetic Inverse Problem.

Goal: Given option prices generated by a known LV surface, recover that
surface using a dual-output PINN.

Pipeline:
    1. Generate ground truth via FDM with the synthetic LV
    2. Sample "observation" points (mimicking market data)
    3. Train dual-output PINN with: data loss + PDE loss + smoothness loss
    4. Validate: compare recovered sigma vs ground truth

Loss:
    L = lam_data * L_data + lam_pde * L_pde + lam_smooth * L_smooth
"""

import sys
import os
import time
import argparse

import torch
import numpy as np

os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

# Add project root to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from phase2_inverse.pinn_dual import (
    PINN_Dual, compute_pde_residual_phase2,
    compute_smoothness_loss, terminal_condition_phase2
)
from phase2_inverse.lv_surface import synthetic_lv_numpy, synthetic_lv_torch
from phase2_inverse.fdm_solver import crank_nicolson_lv, extract_prices_at_observations
from utils.normalization import LogMoneynessNormalizer
from utils.plotting import plot_loss_history
from phase2_inverse.loss_balancer import LossBalancer


# ── Default Parameters ───────────────────────────────────────────────────────

BS_PARAMS = {
    'r': 0.05,
    'q': 0.015,
    'S0': 100.0,  # spot price (only needed for K-to-m conversion)
}

FDM_PARAMS = {
    'm_min': -1.5,
    'm_max': 1.5,
    'N_m': 400,
    'tau_max': 1.0,
    'N_tau': 400,
}

TRAIN = {
    # Observation data
    'n_strikes': 40, # 60,
    'n_maturities': 15, # 30,
    # Collocation points
    'n_pde': 10_000,
    'n_ic': 300,
    # Loss weights (initial)
    'lambda_data': 10.0,
    'lambda_pde': 2.0,
    'lambda_smooth': 0.01,
    'lambda_ic': 1.0,
    # Target Gradient Ratios (Loss Balancer)
    'ratio_data': 8.0,
    'ratio_pde': 2.0,
    'ratio_smooth': 0.1,
    'ratio_ic': 1.0,
    # Adam phase
    'adam_epochs': 15_000,
    'adam_lr': 1e-3,
    # L-BFGS phase
    'lbfgs_iters': 3_000,
    'lbfgs_lr': 1.0,
    'print_every': 500,
}


# ── Data Generation ──────────────────────────────────────────────────────────
# %% Cell: Data Generation

def generate_fdm_data(bs_params, fdm_params, train_cfg):
    """
    Run the FDM solver and extract observation points.

    Returns
    -------
    data : dict with keys:
        m_obs, tau_obs, v_obs : observation points (1D arrays)
        m_fdm, tau_fdm, V_fdm : full FDM surface
    """
    print("  Generating FDM ground truth...")
    t0 = time.time()

    m_fdm, tau_fdm, V_fdm = crank_nicolson_lv(
        sigma_func=synthetic_lv_numpy,
        r=bs_params['r'], q=bs_params['q'],
        m_min=fdm_params['m_min'], m_max=fdm_params['m_max'],
        N_m=fdm_params['N_m'],
        tau_max=fdm_params['tau_max'], N_tau=fdm_params['N_tau']
    )
    print(f"  FDM solved in {time.time() - t0:.1f}s")
    print(f"  FDM grid: {V_fdm.shape[0]} x {V_fdm.shape[1]} points")

    # Generate observation grid (market-like)
    from phase2_inverse.lv_surface import generate_observation_grid
    m_obs, tau_obs, _, _ = generate_observation_grid(
        S0=bs_params['S0'], r=bs_params['r'], q=bs_params['q'],
        n_strikes=train_cfg['n_strikes'],
        n_maturities=train_cfg['n_maturities']
    )

    # Interpolate FDM prices at observation points
    v_obs = extract_prices_at_observations(m_fdm, tau_fdm, V_fdm, m_obs, tau_obs)

    print(f"  Observation points: {len(m_obs)} ({train_cfg['n_strikes']} strikes x "
          f"{train_cfg['n_maturities']} maturities)")

    return {
        'm_obs': m_obs, 'tau_obs': tau_obs, 'v_obs': v_obs,
        'm_fdm': m_fdm, 'tau_fdm': tau_fdm, 'V_fdm': V_fdm,
    }


# ── Collocation Sampling ─────────────────────────────────────────────────────
# %% Cell: Collocation Sampling

def sample_pde_points(n, m_min, m_max, tau_max, device):
    """Sample random interior points for PDE residual."""
    m = m_min + (m_max - m_min) * torch.rand(n, 1, device=device)
    tau = tau_max * torch.rand(n, 1, device=device)
    # Small offset from tau=0 to avoid terminal condition region
    tau = torch.clamp(tau, min=0.01)
    m.requires_grad_(True)
    tau.requires_grad_(True)
    return m, tau


def sample_ic_points(n, m_min, m_max, device):
    """Sample points at tau = 0 for initial/terminal condition."""
    m = m_min + (m_max - m_min) * torch.rand(n, 1, device=device)
    tau = torch.zeros(n, 1, device=device)
    return m, tau


# ── Loss Computation ─────────────────────────────────────────────────────────
# %% Cell: Loss Computation

def compute_loss(model, normalizer, data_tensors, bs_params, fdm_params,
                 train_cfg, device):
    """
    Compute total loss = lam_data*L_data + lam_pde*L_pde
                       + lam_smooth*L_smooth + lam_ic*L_ic.

    Returns (total_loss, dict of individual losses).
    """
    r, q = bs_params['r'], bs_params['q']
    m_min, m_max = fdm_params['m_min'], fdm_params['m_max']
    tau_max = fdm_params['tau_max']

    m_obs, tau_obs, v_obs = data_tensors

    # --- Data loss: match FDM prices at observation points ---
    m_obs_norm, tau_obs_norm = normalizer.normalize(m_obs, tau_obs)
    v_pred, _ = model(m_obs_norm, tau_obs_norm)
    loss_data = torch.mean((v_pred - v_obs) ** 2)

    # --- PDE loss: residual at random interior points ---
    m_pde, tau_pde = sample_pde_points(train_cfg['n_pde'], m_min, m_max,
                                        tau_max, device)
    residual = compute_pde_residual_phase2(model, m_pde, tau_pde,
                                            normalizer, r, q)
    loss_pde = torch.mean(residual ** 2)

    # --- Smoothness loss: Tikhonov on sigma ---
    # Reuse PDE points for efficiency
    loss_smooth = compute_smoothness_loss(model, m_pde, tau_pde, normalizer)

    # --- IC loss: terminal condition at tau = 0 ---
    m_ic, tau_ic = sample_ic_points(train_cfg['n_ic'], m_min, m_max, device)
    m_ic_norm, tau_ic_norm = normalizer.normalize(m_ic, tau_ic)
    v_ic_pred, _ = model(m_ic_norm, tau_ic_norm)
    v_ic_exact = terminal_condition_phase2(m_ic)
    loss_ic = torch.mean((v_ic_pred - v_ic_exact) ** 2)

    losses_tensors = {
        'data': loss_data,
        'pde': loss_pde,
        'smooth': loss_smooth,
        'ic': loss_ic,
    }

    return losses_tensors


# ── Training Loop ────────────────────────────────────────────────────────────
# %% Cell: Training

def train(model, normalizer, data, bs_params, fdm_params, train_cfg,
          device, results_dir='results/phase2'):
    """
    Full training: Adam + L-BFGS.
    """
    os.makedirs(results_dir, exist_ok=True)

    # Prepare data tensors (fixed throughout training)
    m_obs_t = torch.tensor(data['m_obs'], dtype=torch.float32, device=device).unsqueeze(-1)
    tau_obs_t = torch.tensor(data['tau_obs'], dtype=torch.float32, device=device).unsqueeze(-1)
    v_obs_t = torch.tensor(data['v_obs'], dtype=torch.float32, device=device).unsqueeze(-1)
    data_tensors = (m_obs_t, tau_obs_t, v_obs_t)

    history = {'total': [], 'data': [], 'pde': [], 'smooth': [], 'ic': []}
    weight_history = {'data': [], 'pde': [], 'smooth': [], 'ic': []}

    # Initialize Loss Balancer
    init_weights = {
        'data': train_cfg['lambda_data'],
        'pde': train_cfg['lambda_pde'],
        'smooth': train_cfg['lambda_smooth'],
        'ic': train_cfg['lambda_ic']
    }
    target_ratios = {
        'data': train_cfg.get('ratio_data', 1.0),
        'pde': train_cfg.get('ratio_pde', 1.0),
        'smooth': train_cfg.get('ratio_smooth', 1.0),
        'ic': train_cfg.get('ratio_ic', 1.0)
    }
    # Balance gradients with respect to the price network parameters
    balancer = LossBalancer(model.parameters(), init_weights, 
                        target_ratios=target_ratios, alpha=0.9, update_freq=100)



    # ══════════════════════════════════════════════════════════════════════════
    # Phase A: Adam
    # ══════════════════════════════════════════════════════════════════════════
    optimizer = torch.optim.Adam(model.parameters(), lr=train_cfg['adam_lr'])
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=train_cfg['adam_epochs'], eta_min=1e-5
    )

    print("=" * 70)
    print(f"  Phase A: Adam ({train_cfg['adam_epochs']} epochs, lr={train_cfg['adam_lr']})")
    print("=" * 70)
    t0 = time.time()

    for epoch in range(1, train_cfg['adam_epochs'] + 1):
        optimizer.zero_grad()
        losses_tensors = compute_loss(model, normalizer, data_tensors,
                                      bs_params, fdm_params, train_cfg, device)

        # --- Adaptive weight update (every update_freq steps) ---
        # Compute per-component grad norms and update balancer weights.
        # compute_per_component_grad_norms does individual backward passes
        # for each loss, leaves grads zeroed at exit.
        grad_norms = balancer.compute_per_component_grad_norms(losses_tensors)
        weights = balancer.get_weights()
        balancer.update(grad_norms)

        # --- Main backward with current (possibly just-updated) weights ---
        loss = (weights['data'] * losses_tensors['data'] +
                weights['pde'] * losses_tensors['pde'] +
                weights['smooth'] * losses_tensors['smooth'] +
                weights['ic'] * losses_tensors['ic'])
        loss.backward()
        optimizer.step()
        scheduler.step()

        # Record history
        total_item = loss.item()
        history['total'].append(total_item)
        for k in ['data', 'pde', 'smooth', 'ic']:
            history[k].append(losses_tensors[k].item())
            weight_history[k].append(weights[k])

        if epoch % train_cfg['print_every'] == 0 or epoch == 1:
            elapsed = time.time() - t0
            lr_now = optimizer.param_groups[0]['lr']
            print(f"  Epoch {epoch:>5d} | Total={total_item:.3e} | "
                  f"Data={losses_tensors['data'].item():.3e} | PDE={losses_tensors['pde'].item():.3e} | "
                  f"Smooth={losses_tensors['smooth'].item():.3e} | IC={losses_tensors['ic'].item():.3e} | "
                  f"w_pde={weights['pde']:.1f} | lr={lr_now:.2e} | {elapsed:.1f}s")

    adam_time = time.time() - t0
    print(f"\n  Adam finished in {adam_time:.1f}s\n")

    # ══════════════════════════════════════════════════════════════════════════
    # Phase B: L-BFGS
    # ══════════════════════════════════════════════════════════════════════════
    print("=" * 70)
    print(f"  Phase B: L-BFGS ({train_cfg['lbfgs_iters']} max iterations)")
    print("=" * 70)

    lbfgs_optimizer = torch.optim.LBFGS(
        model.parameters(),
        lr=train_cfg['lbfgs_lr'],
        max_iter=train_cfg['lbfgs_iters'],
        max_eval=int(train_cfg['lbfgs_iters'] * 1.25),
        history_size=50,
        tolerance_grad=1e-9,
        tolerance_change=1e-12,
        line_search_fn='strong_wolfe'
    )

    lbfgs_iter = [0]
    t1 = time.time()

    def closure():
        lbfgs_optimizer.zero_grad()
        losses_tensors = compute_loss(model, normalizer, data_tensors,
                                      bs_params, fdm_params, train_cfg, device)
        
        weights = balancer.get_weights()
        loss = (weights['data'] * losses_tensors['data'] +
                weights['pde'] * losses_tensors['pde'] +
                weights['smooth'] * losses_tensors['smooth'] +
                weights['ic'] * losses_tensors['ic'])
                
        loss.backward()

        lbfgs_iter[0] += 1
        total_item = loss.item()
        
        if lbfgs_iter[0] % 100 == 0 or lbfgs_iter[0] == 1:
            print(f"  L-BFGS iter {lbfgs_iter[0]:>5d} | Total={total_item:.3e} | "
                  f"Data={losses_tensors['data'].item():.3e} | PDE={losses_tensors['pde'].item():.3e} | "
                  f"Smooth={losses_tensors['smooth'].item():.3e}")

        history['total'].append(total_item)
        for k in ['data', 'pde', 'smooth', 'ic']:
            history[k].append(losses_tensors[k].item())
            weight_history[k].append(weights[k])

        return loss

    lbfgs_optimizer.step(closure)
    lbfgs_time = time.time() - t1
    print(f"\n  L-BFGS finished in {lbfgs_time:.1f}s ({lbfgs_iter[0]} iterations)\n")

    # ── Save ─────────────────────────────────────────────────────────────────
    total_time = adam_time + lbfgs_time
    print(f"  Total training time: {total_time:.1f}s")

    model_path = os.path.join(results_dir, 'pinn_dual_phase2.pt')
    torch.save({
        'model_state_dict': model.state_dict(),
        'bs_params': bs_params,
        'fdm_params': fdm_params,
        'train_cfg': train_cfg,
        'history': history,
        'weight_history': weight_history,   # saved separately to avoid plot crash
    }, model_path)
    print(f"  Model saved: {model_path}")

    # plot_loss_history only accepts numeric series — pass history without weights
    plot_loss_history(history,
                      save_path=os.path.join(results_dir, 'loss_history.png'),
                      show=False)

    return model, history


# ── Validation ───────────────────────────────────────────────────────────────
# %% Cell: Validation

def validate(model, normalizer, data, bs_params, fdm_params,
             results_dir='results/phase2'):
    """
    Compare recovered sigma against ground truth on a fine grid.

    Pass criterion: |sigma_hat - sigma_true| / sigma_true < 5% for 80% of domain.
    """
    import matplotlib.pyplot as plt

    m_fdm = data['m_fdm']
    tau_fdm = data['tau_fdm']
    V_fdm = data['V_fdm']

    # Evaluation grid (subset of FDM grid, excluding boundaries)
    m_eval = np.linspace(-0.4, 0.4, 100)
    tau_eval = np.linspace(0.05, 0.95, 50)
    m_grid, tau_grid = np.meshgrid(m_eval, tau_eval, indexing='ij')

    m_flat = torch.tensor(m_grid.flatten(), dtype=torch.float32).unsqueeze(-1)
    tau_flat = torch.tensor(tau_grid.flatten(), dtype=torch.float32).unsqueeze(-1)

    model.eval()
    with torch.no_grad():
        m_norm, tau_norm = normalizer.normalize(m_flat, tau_flat)
        v_pred, sigma_pred = model(m_norm, tau_norm)
        sigma_pred = sigma_pred.cpu().numpy().flatten()
        v_pred_np = v_pred.cpu().numpy().flatten()

    # Ground truth
    sigma_true = synthetic_lv_numpy(m_grid.flatten(), tau_grid.flatten())

    # Metrics
    abs_error = np.abs(sigma_pred - sigma_true)
    rel_error = abs_error / sigma_true
    pct_within_5 = np.mean(rel_error < 0.05) * 100
    pct_within_10 = np.mean(rel_error < 0.10) * 100
    max_abs = np.max(abs_error)
    rmse = np.sqrt(np.mean(abs_error**2))
    mae = np.mean(abs_error)

    # Also check price accuracy
    v_true = extract_prices_at_observations(data['m_fdm'], data['tau_fdm'],
                                            data['V_fdm'],
                                            m_grid.flatten(), tau_grid.flatten())
    price_rmse = np.sqrt(np.mean((v_pred_np - v_true)**2))

    # Check IC (Payoff) accuracy at tau=0
    m_ic_eval = np.linspace(-1.5, 1.5, 200)
    m_ic_tensor = torch.tensor(m_ic_eval, dtype=torch.float32).unsqueeze(-1).to(next(model.parameters()).device)
    tau_ic_tensor = torch.zeros_like(m_ic_tensor)
    
    with torch.no_grad():
        m_ic_norm, tau_ic_norm = normalizer.normalize(m_ic_tensor, tau_ic_tensor)
        v_ic_pred, _ = model(m_ic_norm, tau_ic_norm)
        v_ic_pred_np = v_ic_pred.cpu().numpy().flatten()
        
    v_ic_true = np.maximum(np.exp(m_ic_eval) - 1.0, 0.0)
    payoff_rmse = np.sqrt(np.mean((v_ic_pred_np - v_ic_true)**2))

    print("=" * 70)
    print("  Phase 2 Validation: Recovered sigma vs Ground Truth")
    print("=" * 70)
    print(f"\n  Volatility Recovery:")
    print(f"    RMSE(sigma)          : {rmse:.6f}")
    print(f"    MAE(sigma)           : {mae:.6f}")
    print(f"    Max |error|          : {max_abs:.6f}")
    print(f"    Within 5% of true    : {pct_within_5:.1f}%")
    print(f"    Within 10% of true   : {pct_within_10:.1f}%")
    print(f"\n  Price Accuracy:")
    print(f"    RMSE(v)              : {price_rmse:.6f}")
    print(f"    RMSE(payoff)         : {payoff_rmse:.6f}")

    pass_test = pct_within_5 >= 80.0
    print(f"\n  Pass (>80% within 5%)? : {'YES' if pass_test else 'NO'} ({pct_within_5:.1f}%)")
    print()

    os.makedirs(results_dir, exist_ok=True)

    # --- Plot 1: Recovered vs True vol surface ---
    sigma_pred_2d = sigma_pred.reshape(m_grid.shape)
    sigma_true_2d = sigma_true.reshape(m_grid.shape)
    error_2d = abs_error.reshape(m_grid.shape)

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # True surface
    im0 = axes[0].pcolormesh(tau_eval, m_eval, sigma_true_2d, cmap='viridis', shading='auto')
    axes[0].set_xlabel('tau')
    axes[0].set_ylabel('m = ln(S/K)')
    axes[0].set_title('True sigma(m, tau)')
    plt.colorbar(im0, ax=axes[0])

    # Recovered surface
    im1 = axes[1].pcolormesh(tau_eval, m_eval, sigma_pred_2d, cmap='viridis', shading='auto',
                              vmin=im0.get_clim()[0], vmax=im0.get_clim()[1])
    axes[1].set_xlabel('tau')
    axes[1].set_ylabel('m = ln(S/K)')
    axes[1].set_title('Recovered sigma_hat(m, tau)')
    plt.colorbar(im1, ax=axes[1])

    # Error
    im2 = axes[2].pcolormesh(tau_eval, m_eval, error_2d, cmap='hot', shading='auto')
    axes[2].set_xlabel('tau')
    axes[2].set_ylabel('m = ln(S/K)')
    axes[2].set_title(f'|sigma_hat - sigma_true| (max={max_abs:.4f})')
    plt.colorbar(im2, ax=axes[2])

    fig.tight_layout()
    fig.savefig(os.path.join(results_dir, 'vol_surface_comparison.png'), dpi=150)
    print(f"  Saved: {os.path.join(results_dir, 'vol_surface_comparison.png')}")
    plt.close(fig)

    # --- Plot 2: Slice at m=0 (ATM) ---
    atm_idx = np.argmin(np.abs(m_eval))
    fig2, ax2 = plt.subplots(figsize=(8, 5))
    ax2.plot(tau_eval, sigma_true_2d[atm_idx, :], 'b--', linewidth=2, label='True')
    ax2.plot(tau_eval, sigma_pred_2d[atm_idx, :], 'r-', linewidth=1.5, label='PINN')
    ax2.set_xlabel('tau (maturity)', fontsize=13)
    ax2.set_ylabel('sigma', fontsize=13)
    ax2.set_title('ATM Vol Term Structure (m=0)', fontsize=14, fontweight='bold')
    ax2.legend(fontsize=12)
    ax2.grid(True, alpha=0.3)
    fig2.tight_layout()
    fig2.savefig(os.path.join(results_dir, 'atm_term_structure.png'), dpi=150)
    print(f"  Saved: {os.path.join(results_dir, 'atm_term_structure.png')}")
    plt.close(fig2)

    # --- Plot 3: Smile at tau=0.5 ---
    tau_target = 0.5
    tau_idx = np.argmin(np.abs(tau_eval - tau_target))
    fig3, ax3 = plt.subplots(figsize=(8, 5))
    ax3.plot(m_eval, sigma_true_2d[:, tau_idx], 'b--', linewidth=2, label='True')
    ax3.plot(m_eval, sigma_pred_2d[:, tau_idx], 'r-', linewidth=1.5, label='PINN')
    ax3.set_xlabel('m = ln(S/K)', fontsize=13)
    ax3.set_ylabel('sigma', fontsize=13)
    ax3.set_title(f'Vol Smile at tau={tau_eval[tau_idx]:.2f}', fontsize=14, fontweight='bold')
    ax3.legend(fontsize=12)
    ax3.grid(True, alpha=0.3)
    fig3.tight_layout()
    fig3.savefig(os.path.join(results_dir, 'vol_smile.png'), dpi=150)
    print(f"  Saved: {os.path.join(results_dir, 'vol_smile.png')}")
    plt.close(fig3)

    # --- Plot 4: Payoff Check at tau=0 ---
    fig4, ax4 = plt.subplots(figsize=(8, 5))
    ax4.plot(m_ic_eval, v_ic_true, 'b--', linewidth=2, label='True Payoff')
    ax4.plot(m_ic_eval, v_ic_pred_np, 'r-', linewidth=1.5, label='PINN Predicted')
    ax4.set_xlabel('m = ln(S/K)', fontsize=13)
    ax4.set_ylabel('Normalized Price', fontsize=13)
    ax4.set_title('Payoff Condition Check (tau=0)', fontsize=14, fontweight='bold')
    ax4.legend(fontsize=12)
    ax4.grid(True, alpha=0.3)
    fig4.tight_layout()
    fig4.savefig(os.path.join(results_dir, 'payoff_check.png'), dpi=150)
    print(f"  Saved: {os.path.join(results_dir, 'payoff_check.png')}")
    plt.close(fig4)

    return {
        'rmse_sigma': rmse, 'mae_sigma': mae, 'max_abs_sigma': max_abs,
        'pct_within_5': pct_within_5, 'pct_within_10': pct_within_10,
        'rmse_price': price_rmse,
    }


# ── Main ─────────────────────────────────────────────────────────────────────
# %% Cell: Main

def main():
    parser = argparse.ArgumentParser(description='Train Phase 2 Synthetic Inverse PINN')
    parser.add_argument('--adam-epochs', type=int, default=TRAIN['adam_epochs'])
    parser.add_argument('--lbfgs-iters', type=int, default=TRAIN['lbfgs_iters'])
    parser.add_argument('--results-dir', type=str, default='results/phase2')
    parser.add_argument('--seed', type=int, default=42)
    args = parser.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}")

    train_cfg = TRAIN.copy()
    train_cfg['adam_epochs'] = args.adam_epochs
    train_cfg['lbfgs_iters'] = args.lbfgs_iters

    # 1. Generate FDM data
    data = generate_fdm_data(BS_PARAMS, FDM_PARAMS, train_cfg)

    # 2. Build model
    model = PINN_Dual().to(device)
    normalizer = LogMoneynessNormalizer(
        m_scale=0.5,
        tau_max=FDM_PARAMS['tau_max']
    )

    n_params = sum(p.numel() for p in model.parameters())
    print(f"\nModel: {n_params} parameters")
    print(f"BS params: r={BS_PARAMS['r']}, q={BS_PARAMS['q']}")
    print(f"Domain: m in [{FDM_PARAMS['m_min']}, {FDM_PARAMS['m_max']}], "
          f"tau in [0, {FDM_PARAMS['tau_max']}]")
    print()

    # 3. Train
    model, history = train(model, normalizer, data, BS_PARAMS, FDM_PARAMS,
                           train_cfg, device, results_dir=args.results_dir)

    # 4. Validate
    print()
    metrics = validate(model, normalizer, data, BS_PARAMS, FDM_PARAMS,
                       results_dir=args.results_dir)

    print("\nPhase 2 complete.")


if __name__ == '__main__':
    main()
